In [ ]:
print("Hello world")

Hello world


In [ ]:
a = 10
b = 20

In [ ]:
print(a+b)

30


<h1> Hello world </h1>

## Hello world 2
### Hello world 3

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
import tensorflow as tf

## Read CSV files

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/sukamal1928/Machine_Learning_Cheat_Sheets/master/house.csv")

In [ ]:
df.head()

id             date     price  ...     long  sqft_living15  sqft_lot15
0  7129300520  20141013T000000  221900.0  ... -122.257           1340        5650
1  6414100192  20141209T000000  538000.0  ... -122.319           1690        7639
2  5631500400  20150225T000000  180000.0  ... -122.233           2720        8062
3  2487200875  20141209T000000  604000.0  ... -122.393           1360        5000
4  1954400510  20150218T000000  510000.0  ... -122.045           1800        7503

[5 rows x 21 columns]

### read from local system

In [ ]:
from google.colab import files
files.upload()

Saving cars.csv to cars.csv


{'cars.csv': b'symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price\n3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495\n3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500\n1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500\n2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950\n2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450\n2,?,audi,gas,sedan,fwd,front,66.3,53.1,ohc,136,110,19,25,15250\n1,158,audi,gas,sedan,fwd,front,71.4,55.7,ohc,136,110,19,25,17710\n1,?,audi,gas,wagon,fwd,front,71.4,55.7,ohc,136,110,19,25,18920\n1,158,audi,gas,sedan,fwd,front,71.4,55.9,ohc,131,140,17,20,23875\n0,?,audi,gas,hatchback,4wd,front,67.9,52,ohc,131,160,16,22,12000\n2,192,bmw,gas,sedan,rwd,front,64.8,54.3,ohc,108,101,23,29,16430\n0,192,bmw,gas,sedan,rwd,front,64.8,54.3,ohc,108,101,23,29,16925\n0,188,

In [ ]:
df = pd.read_csv("cars.csv")

In [ ]:
df.head()

symboling normalized-losses         make  ... city-mpg highway-mpg  price
0          3                 ?  alfa-romero  ...       21          27  13495
1          3                 ?  alfa-romero  ...       21          27  16500
2          1                 ?  alfa-romero  ...       19          26  16500
3          2               164         audi  ...       24          30  13950
4          2               164         audi  ...       18          22  17450

[5 rows x 15 columns]

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.2.0


In [ ]:
c1 = tf.constant(3)
c2 = tf.constant([10,20])
c3 = tf.constant([[10,20],[30,40]])

In [ ]:
c1

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
id(c1)

140234806063344

In [ ]:
c2

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [ ]:
c3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
print(c1.numpy())

3


In [ ]:
print(c2.numpy())

[10 20]


In [ ]:
print(c3.numpy())

[[10 20]
 [30 40]]


In [ ]:
c1 = c1 + 2

In [ ]:
c1

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
type(c1)

int

In [ ]:
v1 = tf.Variable(4)
v1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4>

In [ ]:
v1 = v1 + 1
id(v1)

140234810033880

In [ ]:
c1.numpy()

AttributeError: ignored

In [ ]:
type(c1)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
c1 = 5

In [ ]:
c1 = tf.constant(3)

In [ ]:
c1

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
type(c1)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
c1 = 4

In [ ]:
type(c1)

int

In [ ]:
c1 = tf.constant(3)

In [ ]:
c1

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
c1 = c1 + 4

In [ ]:
c1

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
v1 = tf.Variable(2)
v2 = tf.Variable([10,20,])
v3 = tf.Variable([[10,20],[30,40]])

In [ ]:
v1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>

In [ ]:
type(v1)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [ ]:
v1.assign(4)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=4>

In [ ]:
v1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>

In [ ]:
type(v1)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [ ]:
v1.assign(4)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=4>

In [ ]:
v1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4>