In [ ]:
'''The matrix factorization of user and item matrices can be generated when the
math cost function RMSE is minimized through matrix factorization. Following 
the above mathematic concept, gradient descent is one of the methods to 
minimize RMSE through each iteration.'''

# Practical Python Code for Matrix Factorization
'''Below is the python code snippet to conduct the gradient descent algorithm. 
We set a rating matrix with 4 movies given by 6 users. As you can see, 
some users didn’t watch some movies before, so the rating is given as 0 in the
rating.'''

In [1]:
import numpy

def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):
    '''
    R: rating matrix
    P: |U| * K (User features matrix)
    Q: |D| * K (Item features matrix)
    K: latent features
    steps: iterations
    alpha: learning rate
    beta: regularization parameter'''
    Q = Q.T

    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    # calculate error
                    eij = R[i][j] - numpy.dot(P[i,:],Q[:,j])

                    for k in range(K):
                        # calculate gradient with a and beta parameter
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])

        eR = numpy.dot(P,Q)

        e = 0

        for i in range(len(R)):

            for j in range(len(R[i])):

                if R[i][j] > 0:

                    e = e + pow(R[i][j] - numpy.dot(P[i,:],Q[:,j]), 2)

                    for k in range(K):

                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        # 0.001: local minimum
        if e < 0.001:

            break

    return P, Q.T

In [3]:
R = [

     [5,3,0,1],

     [4,0,0,1],

     [1,1,0,5],

     [1,0,0,4],

     [0,1,5,4],
    
     [2,1,3,0],

    ]

R = numpy.array(R)
# N: num of User
N = len(R)
# M: num of Movie
M = len(R[0])
# Num of Features
K = 3

 
P = numpy.random.rand(N,K)
Q = numpy.random.rand(M,K)

 

nP, nQ = matrix_factorization(R, P, Q, K)

nR = numpy.dot(nP, nQ.T)
print(nR)

[[5.07195388 2.67192675 6.32355502 1.00658211]
 [3.94236416 1.60822719 3.83877226 1.00098611]
 [1.10698472 0.62364571 3.20202204 4.97680484]
 [0.95873901 0.63042556 2.87695386 3.98180539]
 [3.09645097 1.53104159 4.83956643 4.0014366 ]
 [1.8704076  1.18096931 3.02604398 0.95595962]]


In [ ]:
'''The predicted matrix is generated below. As you can see, the predicted 
matrix has similar output with the true values, and the 0 ratings are replaced 
with the prediction based on the similar users’ preferences on movies.'''