In [1]:
import numpy as np

In [2]:
#in numpy : create a single dimensional array : - means many rows means
# many records but only one column
#to create a single dimensional numpy array []
A=np.array([67,89,45,90,86,98,34,68])

In [3]:
print(A)

[67 89 45 90 86 98 34 68]


In [4]:
#Access data Through Indexing
#To access data at index 2
A[2]

45

In [5]:
#To access data at index -2
A[-2]

34

In [ ]:
#Access data from array A through slicing 
#arrayname[start:stop:step] 
#if no mension start by default start=0
#stop means stop-1  and if no mension stop then goes to till end
#step by default +1 if no mension


In [7]:
A

array([67, 89, 45, 90, 86, 98, 34, 68])

In [6]:
#Access data from numpy array A from 2nd index to 5th index
A[2:6]  #step +1  stop=6-1=5th index

array([45, 90, 86, 98])

In [8]:
A[:6] #means start=0 stop=6-1=5 and increment by +1

array([67, 89, 45, 90, 86, 98])

In [9]:
A[3:] #means start=3 and stop=goes to till end and step =+1

array([90, 86, 98, 34, 68])

In [10]:
A

array([67, 89, 45, 90, 86, 98, 34, 68])

In [11]:
A[2:7:2]

array([45, 86, 34])

In [12]:
A[:-2]  #start=0  stop=-2-1=-3  step=+1

array([67, 89, 45, 90, 86, 98])

In [13]:
#property of numpy array 
#ndim means no. of dimension means how many no. of dimension
A.ndim 

1

In [14]:
A.shape  #shape inbuilt methods to show no. of rows but 1 column (1 D)

(8,)

In [15]:
A.itemsize #itemsize inbuilt method , to show , how many bytes to consume
#each element

4

In [16]:
A.size  #size inbuilt method , to show no. of elements in 1 D array

8

In [17]:
A

array([67, 89, 45, 90, 86, 98, 34, 68])

In [19]:
A.nbytes #to show no. of bytes occupied by Array A

32

In [24]:
A.dtype # to show datatypes of 1D array A

dtype('int32')

In [20]:
#suppose we create a numpy 1 D array
X=np.array([12,32,42.5,89,76,90])

In [21]:
print(X)

[12.  32.  42.5 89.  76.  90. ]


In [22]:
X.dtype

dtype('float64')

In [25]:
#suppose we create a numpy 1 D array
X=np.array([12,32,42.5,89,76,90],int) #compulsory each element : int type

In [26]:
print(X)

[12 32 42 89 76 90]


In [28]:
#replace the value at index 2 with value 98
X[2]=98

In [29]:
print(X)

[12 32 98 89 76 90]


In [30]:
#sum of elements of numpy 1 D array X then use inbuilt function sum()
X.sum()

397

In [33]:
#logic of python (use for loop)
s=0
for i in X:
    s=s+i    #s=0+12=12  s=12+32=44 s=44+98=
print("sum of elements of numpy array X : ",s)
avg=s/6
print(avg)

sum of elements of numpy array X :  397
66.16666666666667


In [32]:
#to find the average means find mean of element of numpy array X
#mean() inbuilt function of numpy library
X.mean()

66.16666666666667