In [1]:
import numpy as np #np alias name

In [2]:
#Create a single dimensional array use array([])  [ ]  means single dimensional
a=np.array([34,56,78,90,16])

In [3]:
print(a)

[34 56 78 90 16]


In [4]:
#python numpy operations 

In [5]:
#to show no. of dimension then use inbuilt method ndim
print(a.ndim)

1


In [6]:
#shape : to show no. of rows
a.shape

(5,)

In [7]:
#To show datatype of numpy array a
a.dtype

dtype('int32')

In [8]:
x=np.array([10,20.50,90,35,67])

In [9]:
print(x)

[10.  20.5 90.  35.  67. ]


In [10]:
x.dtype

dtype('float64')

In [11]:
a=np.array([23,56.78,"anu",89])

In [12]:
a.dtype   #U32 means utf means uniform text format 32 bits

dtype('<U32')

In [13]:
a=np.array([10,20,30,40,50])

In [14]:
#Find the no. of elements
a.size

5

In [15]:
a.dtype

dtype('int32')

In [16]:
a.itemsize #to show memory size of only one item

4

In [17]:
a.nbytes #to find no. of bytes of numpy array a

20

In [18]:
a=np.array([23,56.78,"anu",89])

In [19]:
a.dtype

dtype('<U32')

In [20]:
a.itemsize

128

In [21]:
a.size

4

In [22]:
a.nbytes

512

In [23]:
S=np.array([20,30,40,50],float)

In [24]:
print(S)

[20. 30. 40. 50.]


In [25]:
S.dtype

dtype('float64')

In [26]:
S=np.array([56.7,10,90,34],int)

In [27]:
print(S)

[56 10 90 34]


In [28]:
print(np.sum(S)) #to sum of all elements means 56+10+90+34

190


In [29]:
print(np.sqrt(S))

[7.48331477 3.16227766 9.48683298 5.83095189]


In [30]:
A=np.array([10,20,30,40,50,60,70,80.90])

In [31]:
#access data from numpy array through indexing
A[1]

20.0

In [32]:
A[-1]

80.9

In [33]:
#access data through slicing
A[2:7] #A[start:stop:step]  step=+1 by default if no mension

array([30., 40., 50., 60., 70.])

In [34]:
#Create Two Dimensional Array with the help of numpy array: [[],[],[]] 

In [35]:
A=np.array([[20,30,40,60],[50,70,60,90],[40,50,66,77]])

In [36]:
print(A)

[[20 30 40 60]
 [50 70 60 90]
 [40 50 66 77]]


In [37]:
A.ndim #Show No. of dimension

2

In [38]:
#How many rows and colums in array A
A.shape

(3, 4)

In [39]:
A.dtype

dtype('int32')

In [40]:
#How many elements in array A
A.size

12

In [41]:
A.itemsize

4

In [42]:
#Total bytes occupied by Array A
A.nbytes

48

In [43]:
print(A)

[[20 30 40 60]
 [50 70 60 90]
 [40 50 66 77]]


In [44]:
print(np.sum(A)) #to sum of all elements in Array A

653


In [45]:
print(np.sum(A,axis=0))  #To sum element column wise

[110 150 166 227]


In [46]:
print(np.sum(A,axis=1)) #to sum element row wise

[150 270 233]


In [ ]:
#Access data from two dimensioanl array 
#1. Indexing 

In [48]:
print(A)

[[20 30 40 60]
 [50 70 60 90]
 [40 50 66 77]]


In [47]:
print(A[1][2])  #to access data at 1st row and 2nd column

60


In [54]:
print(A[1:2,:]) #access all details(all columns) of 1st index

[[50 70 60 90]]


In [ ]:
#Arithmetic operations 

In [1]:
import numpy as np

In [3]:
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
Y=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [4]:
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(Y)


[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [6]:
X+Y

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [7]:
np.add(X,Y)

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [8]:
X-Y

array([[ -9, -18, -27],
       [-36, -45, -54],
       [-63, -72, -81]])

In [9]:
np.subtract(X,Y)

array([[ -9, -18, -27],
       [-36, -45, -54],
       [-63, -72, -81]])

In [13]:
X/Y


array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [14]:
np.divide(X,Y)

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [ ]:
#Boardcasting in numpy

In [15]:
A=np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])

In [16]:
print(A)


[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


In [17]:
B=np.array([10,20,30,40])

In [18]:
B

array([10, 20, 30, 40])

In [19]:
A+B

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43],
       [14, 24, 34, 44]])

In [ ]:
#to create single dimensional array (second method) use arange(start,stop,step)

In [20]:
a=np.arange(10,21,1)

In [21]:
print(a)

[10 11 12 13 14 15 16 17 18 19 20]


In [22]:
#to print this array in reverse order
a[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [23]:
#reshape()
#for eg.
x=np.arange(8) 

In [24]:
print(x)

[0 1 2 3 4 5 6 7]


In [26]:
b=x.reshape(4,2) #to change single dimensional to 2 D array

In [27]:
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [ ]:
#WAP to create 3*3 matrix with values ranging 2 to 10

In [28]:
a=np.arange(2,11)

In [29]:
print(a)

[ 2  3  4  5  6  7  8  9 10]


In [30]:
b=a.reshape(3,3)

In [31]:
print(b)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
#Binary operation 

In [32]:
b>5

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [33]:
b[b>5] #b[condition]

array([ 6,  7,  8,  9, 10])

In [34]:
#Vectorisation
a=np.array([1,2,3,4])

In [35]:
print(a)

[1 2 3 4]


In [36]:
x=5

In [37]:
a+x

array([6, 7, 8, 9])

In [39]:
a=np.zeros(6) #1D array create zeros array

In [40]:
a

array([0., 0., 0., 0., 0., 0.])

In [41]:
a=np.zeros(6,int) 

In [42]:
a

array([0, 0, 0, 0, 0, 0])

In [43]:
a[2]=90 #update at 2nd index with 90


In [44]:
a

array([ 0,  0, 90,  0,  0,  0])

In [45]:
a=np.ones(8)

In [46]:
a

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
#2D  create zeros array
a=np.zeros((3,3))

In [50]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
a[1][2]=45


In [52]:
a

array([[ 0.,  0.,  0.],
       [ 0.,  0., 45.],
       [ 0.,  0.,  0.]])

In [ ]:
#Identity matrix
'''2*2 matrix
1 0
0 1

3*3
1 0 0
0 1 0
0 0 1'''

In [53]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
a=np.array([10,20,30])
b=np.array([40,50,60])
c=np.array([70,80,90])

In [55]:
print(a)

[10 20 30]


In [58]:
print(b)

[40 50 60]


In [57]:
print(c)

[70 80 90]


In [62]:
#concatenate means to join 2 ot more array
d=np.concatenate((a,b,c))

In [63]:
print(d)

[10 20 30 40 50 60 70 80 90]


In [64]:
#version of numpy
print(np.__version__)

1.16.4
