In [1]:
import numpy as np 

In [ ]:
#array is a homogenous data type means collection of similar type of data
#there are 2 types of array create in numpy
# 1. single dimensional array
# 2. multidimensional array 

#1. single dimensional array : many rows means many records but only one column
#to create a singledimensional array ==>array() -->inbuilt function
# [] ==>symbol for array

In [3]:
A=np.array([4,6,7,8,90])  #integer type 
#A is user defined array object

In [4]:
print(A)

[ 4  6  7  8 90]


In [6]:
b=np.array([5,7.8,9,23,16])

In [7]:
print(b)

[ 5.   7.8  9.  23.  16. ]


In [8]:
a=np.array([6,7.8,9,12],int)

In [9]:
print(a)

[ 6  7  9 12]


In [10]:
a=np.array([3,4,6,89,23],float)

In [11]:
print(a)

[ 3.  4.  6. 89. 23.]


In [ ]:
#attributes/property  of numpy array 

In [12]:
a.dtype #to represent the datatype of numpy array a 
#dtype ==>inbuilt method 

dtype('float64')

In [13]:
A=np.array([4,6,7,8,90])

In [14]:
A.dtype   #1 byte=8 bits

dtype('int32')

In [15]:
A.size #to show the no. of elements in array object 

5

In [ ]:
#nbytes ==> to show the no. of bytes occupied of array object A

In [16]:
A.nbytes

20

In [17]:
print(A.itemsize) #to show occupied bytes of each element of array object

4

In [18]:
n=A.size*A.itemsize

In [19]:
print(n)

20

In [ ]:
#there are  2 methods  to use to retrieve data from array object
#1. through indexing
#2. through slicing 

In [20]:
print(A)

[ 4  6  7  8 90]


In [21]:
#to retrieve data at index 2
A[2]

7

In [22]:
A[1:4] #to retrieve data from array object through slicing 
# to retrieve data at index 1st index,2nd index,3rd index

array([6, 7, 8])

In [23]:
A[1:4:2] # to retrieve data at index 1st index,3rd index ,5th index and so on

array([6, 8])

In [24]:
A[2:] # to retrieve data at index 2 to till end

array([ 7,  8, 90])

In [25]:
A[:4] #to retrueve data at index start with 0th and stop=4-1=3

array([4, 6, 7, 8])

In [26]:
print(A)

[ 4  6  7  8 90]


In [27]:
print(A[-1]) #to retrieve data through -ve index


90


In [28]:
print(A)

[ 4  6  7  8 90]


In [33]:
#attributes/property of numpy array
A.ndim #ndim inbuilt method ==>to show no. of dimension 

1

In [34]:
A.shape #shape inbuilt method ==>to show the no. of rows and columns
#output show in tuple ( ,)

(5,)

In [ ]:
#Arithmetic operation in Single dimensional array

In [29]:
A.sum() #to sum of all elements of array

115

In [30]:
A.max() #to show maximum element from array

90

In [35]:
A.min()


4

In [36]:
print(A)

[ 4  6  7  8 90]


In [ ]:
#statistics function

In [37]:
A.mean()

23.0

In [38]:
A.std() #standard deviation 

33.52610922848042

In [41]:
print(np.cov(A)) #co-variance

1405.0


In [42]:
A.var() # find variance 

1124.0

In [43]:
print(np.median(A))

7.0


In [ ]:
#zeros matrix (single dimensional array)


In [45]:
Z=np.zeros(6) #bydefault datatype of zeros matrix ==>float

In [46]:
print(Z)

[0. 0. 0. 0. 0. 0.]


In [48]:
Z.dtype

dtype('float64')

In [49]:
A=np.zeros(4,int)

In [50]:
print(A)

[0 0 0 0]


In [51]:
A.dtype

dtype('int32')

In [52]:
A[1]

0

In [53]:
A[1]=90 #to replace data at index 1

In [54]:
print(A)

[ 0 90  0  0]


In [ ]:
#ones matrix


In [55]:
A=np.ones(6) #bydefault float

In [56]:
print(A)

[1. 1. 1. 1. 1. 1.]


In [57]:
A=np.ones(6,int)

In [58]:
print(A)

[1 1 1 1 1 1]


In [59]:
A.ndim

1

In [60]:
A.shape

(6,)

In [61]:
A=np.empty(5)

In [62]:
print(A)

[ 361.  289.  256.  225. 4489.]


In [63]:
A[2]=76

In [64]:
print(A)

[ 361.  289.   76.  225. 4489.]


In [ ]:
#create two dimensional array array([[],[],[]])
#two dimansional array means to store data in the matrix form 
#means many rows and in each row many columns 
# [[ ],[ ],[ ]]

In [65]:
A=np.array([[2,3,4,5],[9,8,7,6],[12,45,60,20]])

In [66]:
print(A)

[[ 2  3  4  5]
 [ 9  8  7  6]
 [12 45 60 20]]


In [67]:
A.shape #to show no. of rows and columns

(3, 4)

In [68]:
A.ndim #to show dimensional of array

2

In [69]:
A.itemsize #to size of each element of array in bytes

4

In [70]:
A.size #to show no. of elements in array A

12

In [71]:
A.nbytes #to show no. of bytes occupied by A matrix 

48

In [72]:
print(A)

[[ 2  3  4  5]
 [ 9  8  7  6]
 [12 45 60 20]]


In [ ]:
# to retrieve data from Array A through indexing
#to access element at 1st row and 2nd column

In [73]:
A[1,2]

7

In [74]:
A[-2,-1]  

6

In [ ]:
# to retrieve data from Array A through slicing

In [75]:
print(A)

[[ 2  3  4  5]
 [ 9  8  7  6]
 [12 45 60 20]]


In [76]:
A[:2] #A[row range,column range] 
#here row range =[:2] start row=1 and end row=2-1=1 and no mension column
#means to access all values(means value of all columns) of 0th row and 1st row 

array([[2, 3, 4, 5],
       [9, 8, 7, 6]])

In [78]:
A[:,1:3] #here to all values display 1st and 2nd column of all rows

array([[ 3,  4],
       [ 8,  7],
       [45, 60]])

In [81]:
print(A)

[[ 2  3  4  5]
 [ 9  8  7  6]
 [12 45 60 20]]


In [80]:
A[:,2] #value of all row at 2nd col

array([ 4,  7, 60])

In [82]:
A[-1:,-2]  # to retrieve value at -1 row and -2 column means cell's value

array([60])

In [ ]:
#arithmetic operation in two dimensional array

In [ ]:
#sum() ==>to sum of all elements of two dimensional array

In [83]:
print(A)

[[ 2  3  4  5]
 [ 9  8  7  6]
 [12 45 60 20]]


In [84]:
A.sum() #to sum all element of array

181

In [85]:
A.sum(axis=1) #sum of element rowwise

array([ 14,  30, 137])

In [86]:
A.sum(axis=0) #sum of element column wise

array([23, 56, 71, 31])

In [87]:
print(A)

[[ 2  3  4  5]
 [ 9  8  7  6]
 [12 45 60 20]]


In [88]:
A.max()

60

In [89]:
A.max(axis=1) #to display maximum value at rowwise

array([ 5,  9, 60])

In [90]:
A.max(axis=0) #to display maximum value at col wise

array([12, 45, 60, 20])

In [ ]:
#zeros array(two dimensional array)

In [95]:
X=np.zeros((3,4),int)

In [96]:
print(X)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [93]:
X[2,3]=90 #to update value at 2nd row and 3rd column

In [94]:
print(X)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0. 90.]]


In [97]:
B=np.ones((3,3))

In [98]:
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [99]:
C=np.empty((4,5))

In [100]:
print(C)

[[1.11129791e-311 6.27463370e-322 0.00000000e+000 0.00000000e+000
  1.89146896e-307]
 [5.30276956e+180 1.57076922e-076 6.98610466e-076 3.65725690e-086
  3.35659044e-143]
 [6.01433264e+175 6.93885958e+218 5.56218858e+180 3.94356143e+180
  6.64087898e-066]
 [3.11099395e+179 1.43471613e-051 1.45168425e-051 7.17521555e-144
  1.50008929e+248]]


In [ ]:
#identity matrix I always a square matrix 
#identity always work on two dimensional array

In [101]:
np.eye((3)) #in identity matrix , row and column are same 
#here 3 means 3 row and 3 column

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [102]:
np.eye((3),dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
#other way to create a matrix ==>single dimensional array
#arange() ==>inbuilt function of numpy array ==>this function work as
#range() of python
#arange(start,stop,step)
#in python ==>range(start,stop,step)

In [103]:
A=np.arange(10,20) #start=10 stop=20-1=19 here no mension step
#then by default increment by 1 means step=+1 

In [104]:
print(A)

[10 11 12 13 14 15 16 17 18 19]


In [105]:
A=A.reshape(5,2)  #to convert single dimensional array to two dimensional array

In [106]:
print(A)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [107]:
A=np.arange(20,30).reshape(2,5)

In [108]:
print(A)

[[20 21 22 23 24]
 [25 26 27 28 29]]


In [109]:
A=np.arange(10,101,2) #to create a single dimensional array of even no.
#from 2 to  100

In [110]:
print(A)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]
