In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [2]:
data=pd.read_csv('pos_salary.csv')

In [3]:
data

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2             Senior      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-Level      9   500000
9                CEO     10  1000000

In [4]:
x=data.iloc[:,1:2].values #x=data[["Level"]]

In [5]:
y=data.iloc[:,2].values  #y=data["Salary"]

In [6]:
y

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000], dtype=int64)

In [7]:
lr=LinearRegression()

In [8]:
lr.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
y_pred=lr.predict([[6.5]])

In [10]:
y_pred

array([330378.78787879])

In [11]:
#Create the object of  PolynomialFeatures
pf= PolynomialFeatures(5) #pass How much degree 

In [12]:
x_poly=pf.fit_transform(x) 
print(pd.DataFrame(x_poly)) #y=b0x^0+b1x1+b2(x1^2)

     0     1      2       3        4         5
0  1.0   1.0    1.0     1.0      1.0       1.0
1  1.0   2.0    4.0     8.0     16.0      32.0
2  1.0   3.0    9.0    27.0     81.0     243.0
3  1.0   4.0   16.0    64.0    256.0    1024.0
4  1.0   5.0   25.0   125.0    625.0    3125.0
5  1.0   6.0   36.0   216.0   1296.0    7776.0
6  1.0   7.0   49.0   343.0   2401.0   16807.0
7  1.0   8.0   64.0   512.0   4096.0   32768.0
8  1.0   9.0   81.0   729.0   6561.0   59049.0
9  1.0  10.0  100.0  1000.0  10000.0  100000.0


In [13]:
lr=LinearRegression()
lr.fit(x_poly,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
#We can perform the prediction then call predict()
#y_pred=lr.predict([[1,6.5,(6.5**2),(6.5**3),(6.5**4)]]) # lr.predict([[lx**0,x_test,x_test**2]])


In [15]:
y_pred=lr.predict(x_poly)

In [16]:
y_pred

array([ 43895.1048956 ,  53836.82983705,  57065.26806523,  77286.71328647,
       112263.40326306, 152736.59673623, 201349.65034936, 291571.09557096,
       506617.71561785, 998377.62237821])

In [17]:
mean_squared_error(y,y_pred)


16382284.382283146

In [18]:
r2_score(y,y_pred)

0.9997969027099755